requirejs.config({
  //baseUrl: 'bower_components',
  paths:{
    'domReady':'../bower_components/domReady/domReady',
    'angular':'../bower_components/angular/angular.min',
    'uiRouter':'../bower_components/angular-ui-router/release/angular-ui-router.min',
    //'bootstrap':'bootstrap/dist/js/bootstrap.min',
    'jquery':'../bower_components/jquery/dist/jquery.min'
  },
  shim:{
    'jquery':{
      exports:'$'
    },
    'angular':{
      deps:['jquery'],
      exports:'angular'
    },
    'uiRouter':{
      deps:['angular']
    }/*,
    'bootstrap':{
      deps:['jquery']
    }*/
  },
  deps:['../js/bootstrap']
});
