requirejs.config({
   //baseUrl: '/',
   paths:{
      'domReady':'../vendor/domReady/domReady',
      'angular':'../vendor/angular/angular.min',
      'uiRouter':'../vendor/angular-ui-router/release/angular-ui-router.min',
      'jquery':'../vendor/jquery/dist/jquery.min',
      'ngDraggable': '../vendor/ngDraggable/ngDraggable',
      'bootstrap':'../vendor/bootstrap/dist/js/bootstrap.min'
   },
   shim:{
      'jquery':{
         exports:'$'
      },
      'bootstrap':{
         deps:['jquery']
      },
      'angular':{
         deps:['jquery'],
         exports:'angular'
      },
      'uiRouter':{
         deps:['angular']
      },
      'ngDraggable':{
         deps:['angular'],
         exports:'ngDraggable'
      }
   },
   deps:['../js/main']
});
